// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uznfzqrcnazottcquodj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6bmZ6cXJjbmF6b3R0Y3F1b2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTYzMjQsImV4cCI6MjA2NTQ5MjMyNH0.c_bpP97mHoWG-BegPiuhHCCIIMlaxa8lqW4OqPd4dK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);